FROM postgres:12-alpine

# Copy in the load-extensions script
COPY load-extensions.sh /docker-entrypoint-initdb.d/
# COPY startup.sql /docker-entrypoint-initdb.d/



# Add the certs and change permissions
ADD cert.pem /etc/ssl/certs/cert.pem
ADD key.pem /etc/ssl/private/key.pem
# ADD chain.pem /etc/ssl/private/chain.pem

RUN chmod 400 /etc/ssl/private/key.pem