FROM postgres:12-alpine

# Copy in the load-extensions script
# COPY load-extensions.sh /docker-entrypoint-initdb.d/
COPY ./db/schema.sql /docker-entrypoint-initdb.d/



# Add the certs and change permissions
ADD server.crt /var/lib/postgresql/server.crt
ADD server.key /var/lib/postgresql/server.key
ADD chain.pem /var/lib/postgresql/chain.pem


RUN chown 70:70 /var/lib/postgresql/server.key
RUN chmod 600 /var/lib/postgresql/server.key