version: "3"
services:
  fg-redis:
    image: redis
    volumes:
      - ${REDIS_DB_PATH}:/data
    # ports:
    #   - "6379:6379"
  fg-db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    container_name: ${CONTAINER_DB_NAME}
    restart: on-failure
    # image: ${FGAPI_POSTGRES_IMAGE}
    environment:
      # SSL_CERT_FILE: ${SSL_CERT_FILE}
      # SSL_KEY_FILE: ${SSL_KEY_FILE}
      # SSL_CA_FILE: ${SSL_CHAIN_FILE}
      ALLOW_IP_RANGE: 0.0.0.0/0
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      VIRTUAL_PORT: ${FGAPI_VIRTUAL_PORT}
      # POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting

    volumes:
      - ${DB_PATH}:/var/lib/postgresql/12/main
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  fg-api:
    image: ${PGAPI_IMAGE}
    expose:
      - 80
    depends_on:
      - fg-redis
      - fg-db
    command:
      ["./wait-for-it.sh", "pg-db:5432", "--", "node", "/app/dist/index.js"]
    environment:
      VIRTUAL_PORT: ${FGAPI_VIRTUAL_PORT}
      VIRTUAL_HOST: ${PRODUCTION_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      PORT: ${FGAPI_VIRTUAL_PORT}
      GRAPHQL_ENDPOINT: ${GRAPHQL_ENDPOINT}
      SESSION_SECRET: ${SESSION_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT_NUMBER: ${REDIS_PORT_NUMBER}
      AT_DB_HOST: ${PG_DB_HOST}
      AT_DB_PORT: ${PG_DB_PORT}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      TYPEORM_SYNCHRONIZE: "false"
      TYPEORM_LOGGING: "false"
      PRODUCTION_CLIENT_ORIGIN: ${PRODUCTION_CLIENT_ORIGIN}
      PRODUCTION_API_ORIGIN: ${PRODUCTION_API_ORIGIN}
      BUILD_FLAG: ${BUILD_FLAG}
      POSTMARK_API_TOKEN: ${POSTMARK_API_TOKEN}
    ports:
      - "${FGAPI_VIRTUAL_PORT}:${FGAPI_VIRTUAL_PORT}"

networks:
  default:
    external:
      name: ${NETWORK}
